/*
 * Generated By @MgkMshrmBrkfst forked from woocommerce-sats
 * If you find value with this code, please tip me some Monero at 83oKzkbUWJyZyjGuZv9yTyYWSgHa8SKn4KgcngWVD1eFW1dzpqP77TnaNngDg1hkwHHvJY8X7wsyC9fKpekSa9gc9niwqR7
 * You can also purchase goodies with Monero and Bitcoin at https://www.cryptotechcastle.com
 *
 * To use, copy the code below these comments and add to your Wordpress Child theme's function.php file.
 * You must use WooCommerce as your store plugin and obviously a Monero and Bitcoin payment gateway to receieve those cryptocurrencies.
 * Note this does not change the shipping nor tax, which will both be shown in fiat.
 * Enjoy!
 */

function get_bitcoin_exchange_rate() {
    $api_url = 'https://blockchain.info/ticker';
    $curl = curl_init();
    curl_setopt_array($curl, array(
        CURLOPT_URL => $api_url,
        CURLOPT_RETURNTRANSFER => true
    ));
    $response = curl_exec($curl);
    curl_close($curl);
    $json_data = json_decode($response, true);
    return $json_data['USD']['last'];
}

function get_monero_exchange_rate() {
    $api_url = 'https://api.coingecko.com/api/v3/simple/price?ids=monero&vs_currencies=usd';
    $curl = curl_init();
    curl_setopt_array($curl, array(
        CURLOPT_URL => $api_url,
        CURLOPT_RETURNTRANSFER => true
    ));
    $response = curl_exec($curl);
    curl_close($curl);
    $json_data = json_decode($response, true);
    return $json_data['monero']['usd'];
}

function convert_to_bitcoin($amount) {
    $exchange_rate = get_bitcoin_exchange_rate();
    $bitcoin_amount = $amount / $exchange_rate;
    $satoshi_amount = $bitcoin_amount * 100000000;
    return number_format($satoshi_amount, 0, '.', ',') . ' sats';
}

function convert_to_monero($amount) {
    $exchange_rate = get_monero_exchange_rate();
    $monero_amount = $amount / $exchange_rate;
    return number_format($monero_amount, 3, '.', '') . ' XMR'; // Display Monero amount up to 3 decimal places
}

// Convert product price to Bitcoin, Monero and display USD price
add_filter('woocommerce_get_price_html', 'display_price_in_bitcoin_monero_and_usd', 10, 2);
function display_price_in_bitcoin_monero_and_usd($price, $product) {
    $usd_price = $product->get_price();
    $bitcoin_price = convert_to_bitcoin($usd_price);
    $monero_price = convert_to_monero($usd_price);
    return '<span class="woocommerce-Price-amount amount">' . wc_price($usd_price) . '</span><br><span class="woocommerce-Price-amount amount">' . $bitcoin_price . '</span><br><span class="woocommerce-Price-amount amount">' . $monero_price . '</span>';
}

// And so on for each place you want to display prices...
